version: '3.8'

services:
  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    container_name: core_service
    env_file:
      - ./core/secure.env  # secure.env 파일에서 환경 변수를 읽어옵니다.
    volumes:
      - ~/.aws:/root/.aws:ro
    restart: always
